apiVersion: v1
kind: Secret
metadata:
  name: hammergen-env-variables
  namespace: hammergen-{{ ENV }}
type: Opaque
data:
  FLASK_SECRET_KEY: {{ FLASK_SECRET_KEY }}
  MONGO_URI: {{ MONGO_URI }}
  SENDGRID_API_KEY_2: {{ SENDGRID_API_KEY_2 }}
  RECAPTCHA_SECRET: {{ RECAPTCHA_SECRET }}